### ISSUE TITLE
Add D7SMS 

### ISSUE THREAD

**Issue by d7networks** [YoussefSell/SMS.Net#3]
Hi,

Could you please include D7 SMS also to the Delivery Channels. As a global messaging solutions provider, D7Networks offers extensive coverage for SMS termination, WhatsApp, Viber, Slack messaging, number verification, and number lookup services.

Thanks, 
ILYAS
D7 Networks

**Comment by YoussefSell** [comment]
Support for D7Networks has been added with version 2.0.0, for more details: [SMS.Net.D7Networks](https://github.com/YoussefSell/SMS.Net/tree/master/src/SmsDeliveryChannels/SMS.Net.D7Networks)
